import { euclidCircularB } from '~/lib/fonts'
import type { Metadata } from 'next'
import './globals.css'
import Header from '~/components/Header'
import { Analytics } from '@vercel/analytics/next'

export const metadata: Metadata = {
  title: 'Myxellia',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${euclidCircularB.variable} antialiased`}>
        <Header />
        <main className="pt-3 pb-7 *:mx-auto *:w-11/12 *:max-w-screen-2xl">
          {children}
          <Analytics />
        </main>
      </body>
    </html>
  )
}
